// ============================================================
// Mock data for development (replace with Supabase in prod)
// ============================================================
import { Task, User, WeeklyEvent, ALL_ROLES } from "./types";

export const MOCK_USERS: User[] = ALL_ROLES.map((role, i) => ({
  id: `user-${i + 1}`,
  email: `user${i + 1}@school.kz`,
  full_name: [
    "Айбек Сейткали",
    "Гүлнар Жақсыбекова",
    "Серік Мұқанов",
    "Дина Есенова",
    "Азамат Қалиев",
    "Маржан Өмірбекова",
    "Нұрлан Дүйсенов",
    "Зейнеп Ахметова",
    "Бауыржан Сейтқали",
    "Алия Нұрмағамбетова",
  ][i],
  role,
  is_admin: i === 0,
}));

const today = new Date();
const addDays = (d: number) => {
  const dt = new Date(today);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString().split("T")[0];
};

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Мұғалімдер жиналысын өткізу",
    description: "Апта сайынғы педагогикалық кеңес",
    assignee_id: "user-2",
    assignee: MOCK_USERS[1],
    deadline: addDays(-2),
    priority: "Жоғары",
    status: "Кешікті",
    weekly_plan: true,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-2",
    title: "Сабақ кестесін жаңарту",
    description: "2-тоқсан кестесін бекіту",
    assignee_id: "user-3",
    assignee: MOCK_USERS[2],
    deadline: addDays(1),
    priority: "Жоғары",
    status: "Процесте",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-3",
    title: "Бастауыш сынып олимпиадасын ұйымдастыру",
    description: "1-4 сыныптар арасында олимпиада",
    assignee_id: "user-4",
    assignee: MOCK_USERS[3],
    deadline: addDays(5),
    priority: "Орташа",
    status: "Процесте",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-4",
    title: "Тәрбие жоспарын тапсыру",
    description: "Ай сайынғы тәрбие жоспары",
    assignee_id: "user-5",
    assignee: MOCK_USERS[4],
    deadline: addDays(10),
    priority: "Орташа",
    status: "Орындалды",
    weekly_plan: true,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-5",
    title: "Мектеп газетін шығару",
    assignee_id: "user-6",
    assignee: MOCK_USERS[5],
    deadline: addDays(2),
    priority: "Төмен",
    status: "Процесте",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-6",
    title: "Әдістемелік кеңес есебі",
    assignee_id: "user-7",
    assignee: MOCK_USERS[6],
    deadline: addDays(7),
    priority: "Орташа",
    status: "Орындалды",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-7",
    title: "Бейінді сынып тізімін жаңарту",
    assignee_id: "user-8",
    assignee: MOCK_USERS[7],
    deadline: addDays(3),
    priority: "Жоғары",
    status: "Процесте",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-8",
    title: "Дарынды оқушылар конкурсына қатысу",
    assignee_id: "user-9",
    assignee: MOCK_USERS[8],
    deadline: addDays(14),
    priority: "Жоғары",
    status: "Процесте",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-9",
    title: "Әлеуметтік паспорт жаңарту",
    assignee_id: "user-10",
    assignee: MOCK_USERS[9],
    deadline: addDays(-1),
    priority: "Жоғары",
    status: "Кешікті",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "task-10",
    title: "ҰБТ дайындық есебі",
    assignee_id: "user-2",
    assignee: MOCK_USERS[1],
    deadline: addDays(20),
    priority: "Жоғары",
    status: "Орындалды",
    weekly_plan: false,
    created_by: "user-1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const WEEKLY_EVENTS: WeeklyEvent[] = [
  {
    id: "we-1",
    day: "Дүйсенбі",
    title: "Директор жиналысы",
    time: "08:00",
    responsible: "Директор",
  },
  {
    id: "we-2",
    day: "Дүйсенбі",
    title: "Ту жиналысы",
    time: "08:30",
    responsible: "Тәрбие жөніндегі директор орынбасары 1",
  },
  {
    id: "we-3",
    day: "Сейсенбі",
    title: "Оқу комиссиясы",
    time: "14:00",
    responsible: "Оқу ісі жөніндегі директор орынбасары 1",
  },
  {
    id: "we-4",
    day: "Сәрсенбі",
    title: "Әдістемелік кеңес",
    time: "15:00",
    responsible: "Әдіскер",
  },
  {
    id: "we-5",
    day: "Бейсенбі",
    title: "Бастауыш мектеп жиналысы",
    time: "14:00",
    responsible: "Бастауыш сынып жөніндегі директор орынбасары",
  },
  {
    id: "we-6",
    day: "Жұма",
    title: "Апта қорытындысы",
    time: "15:30",
    responsible: "Директор",
  },
  {
    id: "we-7",
    day: "Жұма",
    title: "Ата-аналар кеңесі",
    time: "17:00",
    responsible: "Тәрбие жөніндегі директор орынбасары 2",
  },
];
